### ISSUE TITLE
Fix the 500 server error when the multisite-accounts plugin misses a master API key

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#223]
The relevant line of code that will lead to the "500 Internal Server Error" crash is [this one](https://github.com/edgeryders/discourse/blob/multisite/plugins/edgeryders-multisite-accounts/plugin.rb#L97).

It happens in case of a request to `multisite_account.json` that includes a request for an API key for a site for which Discourse does not know the master API key, so cannot find it in the line of code referenced above.

The Discourse error log in the admin backend has this about the crash:

```
NoMethodError (undefined method `[]' for nil:NilClass) in 
[…]/plugins/edgeryders-multisite-accounts/plugin.rb:97:in `create_community_account'

stacktrace (most recent first): 

[…]/plugins/edgeryders-multisite-accounts/plugin.rb:97:in `create_community_account' 
[…]/plugins/edgeryders-multisite-accounts/plugin.rb:53:in `block in create' 
[…]/plugins/edgeryders-multisite-accounts/plugin.rb:52:in `map' 
[…]/plugins/edgeryders-multisite-accounts/plugin.rb:52:in `create'
```

**Comment by tanius** [comment]
The same "500 server error" response happens for:

* Requests to API endpoint `multisite_account.json?hostname=…` with a `hostname` parameter that is not even an Edgeryders Communities site, including hostnames that do not even resolve by DNS.

* Requests to the second API endpoint `multisite_account_api_key.json?hostname=…` with a `hostname` parameter for which  Discourse does not know the master API key in order to determine or create the requested API key. Tested with user `matthias` and hostname `forum.burning-stories.org`.

* Requests to the second API endpoint `multisite_account_api_key.json?hostname=…` with a `hostname` parameter that is not even an Edgeryders Communities site, including hostnames that do not even resolve by DNS.

In all of these cases, the server should return an appropriate status code that is not 500 and a suitable error message.
